# Generated by Django 5.2.10 on 2026-01-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='due_date',
            new_name='due_at',
        ),
    ]
