# Generated by Django 5.2.10 on 2026-01-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_due_date_todo_due_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
