# Generated by Django 5.2.10 on 2026-02-04 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_todo_due_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_completed',
            new_name='is_done',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='due_at',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='srno',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.AddField(
            model_name='todo',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='todo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
