# Generated by Django 5.2.10 on 2026-02-04 16:14

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=Home.models.audio_path),
        ),
        migrations.AlterField(
            model_name='todo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=Home.models.video_path),
        ),
    ]
